name: Nodejs-typescript CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types:
      - closed
    branches: [master]

jobs:
  build:
    name: Build Nodejs App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-build
          path: dist/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test -- --watchAll=false

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nodejs-build
          path: build/

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on the server
            cd /home/ubuntu/sites


            # Pull the latest changes from the Git repository
            git pull origin master

            cd nodejs-typescript-ec2-rds

            # Copy the build directory to the server
            rsync -avz --delete dist/ /home/ubuntu/sites/dist/

            # Sync the node_modules directory
            rsync -avz --delete node_modules/ /home/ubuntu/sites/node_modules/

            # Restart the application (using PM2)
            export NVM_DIR=~/.nvm
            source $NVM_DIR/nvm.sh
            pm2 restart all