name: Nodejs-typescript CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types:
      - closed
    branches: [master]

jobs:
  build:
    name: Build Nodejs App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-build
          path: dist/

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nodejs-build
          path: dist/

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Upload dist and node_modules to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*,node_modules/*"
          target: "/home/ubuntu/sites/nodejs-typescript-ec2-rds/"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/sites/nodejs-typescript-ec2-rds/
            export NVM_DIR=~/.nvm
            source $NVM_DIR/nvm.sh
            pm2 restart all
